name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"] # Автосборка при каждом сохранении в ветку main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        # Добавлен флаг для игнорирования конфликтов версий React
        run: npm install --legacy-peer-deps

      - name: Build
        # Команда сборки вашего React-проекта
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist # Папка, куда Vite сохраняет готовый сайт

  deploy:
    needs: build_site
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
